### ISSUE TITLE
Can't change domain for DICOM Web services

### ISSUE THREAD

**Issue by draiberg** [Alvearie/imaging-ingestion#89]
When applying the example configuration mentioned in README.md of Alvearie DICOMweb services configuration the domain applied is always "example.com" so that external endpoint always looks like that: "wadoServiceExternalEndpoint: http://img-ingest-wado.imaging-ingestion.example.com"

The domain in the Istio Virtual Service is set accordingly.

To reproduce just apply configuration mentioned in the README of this repo.

I would also like to change protocol from http to https but that doesn't seem to possible.
Another observation I've made is that there is no external exposure for STOW, only WADO. Is that intended?

**Comment by jeesmon** [comment]
@draiberg `wadoServiceExternalEndpoint` is automatically looked up from the address of the WADO KService. If you run

```
kubectl -n <ns> get ksvc
```

you can see the address generated by knative service.

You can also see the ingress address of the STOW kservice using the same above command and you can connect it to it from your client.

We also have a toolbox docker image that you can use to send images to stow endpoint for testing at https://github.com/Alvearie/imaging-ingestion/tree/main/test-data/toolbox

Please let me if you need more details

**Comment by rduggan-ibm** [comment]
I am going to close this seeing as it has been over three weeks and I believe a satisfactory response was provided.  If this needs to be re-opened, please do.
